/* automatically generated by rust-bindgen 0.59.2 */

// FFI declarations for the legacy closed-source libOpenglRender.so blob.
//
// On aarch64 (real devices), the blob ships in jniLibs/arm64-v8a/ and
// build.rs adds `cargo:rustc-link-lib=dylib=OpenglRender` so the linker
// can resolve these symbols at link time.
//
// On x86_64 (emulator/redroid testing), the legacy blob does NOT exist
// (it's a closed-source ARM64-only binary). The new open-source
// libOpenglRender_new.so from app/rs/openglrenderer/ is the only option.
// We compile out this module on x86_64 so the linker doesn't try to
// link a non-existent blob.
//
// core.rs's `RendererType::Old` dispatch path then becomes unavailable
// on x86_64, which is fine — the new Rust renderer is the only one
// that works there anyway.

#[cfg(target_arch = "aarch64")]
#[allow(dead_code)]
#[link(name = "OpenglRender")]
extern "C" {
    pub fn destroyOpenGLSubwindow() -> ::std::os::raw::c_int;

    pub fn repaintOpenGLDisplay();

    pub fn setNativeWindow(arg1: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;

    pub fn resetSubWindow(
        p_window: *mut ::std::os::raw::c_void,
        wx: ::std::os::raw::c_int,
        wy: ::std::os::raw::c_int,
        ww: ::std::os::raw::c_int,
        wh: ::std::os::raw::c_int,
        fbw: ::std::os::raw::c_int,
        fbh: ::std::os::raw::c_int,
        dpr: f32,
        zRot: f32,
    ) -> ::std::os::raw::c_int;

    pub fn startOpenGLRenderer(
        win: *mut ::std::os::raw::c_void,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        xdpi: ::std::os::raw::c_int,
        ydpi: ::std::os::raw::c_int,
        fps: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;

    pub fn removeSubWindow(arg1: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
}

// On non-aarch64 targets, provide stub declarations so core.rs still
// compiles. These functions will never be called at runtime because
// the dispatch in core.rs only selects RendererType::Old when the user
// opts in via ProfileSettings.useNewRenderer() == false — and on x86_64
// the profile defaults to true (the new renderer is the only option).
//
// If the user does opt into the old renderer on x86_64, the call will
// panic at runtime with "renderer_bindings not available on this
// architecture" rather than failing at link time. This is a much better
// failure mode than a build break.
#[cfg(not(target_arch = "aarch64"))]
#[allow(dead_code, non_snake_case)]
pub mod renderer_bindings {
    use std::os::raw::{c_int, c_void};

    pub fn destroyOpenGLSubwindow() -> c_int {
        panic!("renderer_bindings::destroyOpenGLSubwindow not available on this architecture (legacy libOpenglRender.so is arm64-only)");
    }

    pub fn repaintOpenGLDisplay() {
        panic!("renderer_bindings::repaintOpenGLDisplay not available on this architecture");
    }

    pub fn setNativeWindow(_arg1: *mut c_void) -> c_int {
        panic!("renderer_bindings::setNativeWindow not available on this architecture");
    }

    pub fn resetSubWindow(
        _p_window: *mut c_void,
        _wx: c_int,
        _wy: c_int,
        _ww: c_int,
        _wh: c_int,
        _fbw: c_int,
        _fbh: c_int,
        _dpr: f32,
        _zRot: f32,
    ) -> c_int {
        panic!("renderer_bindings::resetSubWindow not available on this architecture");
    }

    pub fn startOpenGLRenderer(
        _win: *mut c_void,
        _width: c_int,
        _height: c_int,
        _xdpi: c_int,
        _ydpi: c_int,
        _fps: c_int,
    ) -> c_int {
        panic!("renderer_bindings::startOpenGLRenderer not available on this architecture");
    }

    pub fn removeSubWindow(_arg1: *mut c_void) -> c_int {
        panic!("renderer_bindings::removeSubWindow not available on this architecture");
    }
}

// On non-aarch64, re-export the stub module's functions at the crate
// root so the call sites in core.rs (`renderer_bindings::setNativeWindow`)
// still resolve.
#[cfg(not(target_arch = "aarch64"))]
pub use renderer_bindings::*;
