// GL2Decoder.h — minimal stub for the twoyi NDK build.
//
// The full AOSP GL2Decoder is generated by emugen from the GLESv2 spec
// (see GLESv2_dec/GL2Decoder.h in the source tree) and inherits from
// gl2_decoder_context_t.  That generated type pulls in a large dependency
// chain (gl2_dec.h, gl2_server_context.h, GLDecoderContextData, etc.)
// that is not yet wired into the build.
//
// This stub provides just enough of the GL2Decoder interface for the
// files that reference it (ThreadInfo.h, FrameBuffer.cpp) to compile
// when they are brought online.  The class has a single setContextData()
// method that matches the AOSP signature.
#pragma once

class GLDecoderContextData;

class GL2Decoder {
public:
    GL2Decoder() {}
    ~GL2Decoder() {}
    void setContextData(GLDecoderContextData *contextData) {
        (void)contextData;
    }
};
