// GLDecoder.h — minimal stub for the twoyi NDK build.
//
// The full AOSP GLDecoder is generated by emugen from the GLESv1 spec
// (see GLESv1_dec/GLDecoder.h in the source tree) and inherits from
// gl_decoder_context_t.  That generated type pulls in a large dependency
// chain (gl_dec.h, gl_server_context.h, GLDecoderContextData, etc.) that
// is not yet wired into the build.
//
// This stub provides just enough of the GLDecoder interface for the
// files that reference it (ThreadInfo.h, FrameBuffer.cpp) to compile
// when they are brought online.  The class has a single setContextData()
// method that matches the AOSP signature.
#pragma once

class GLDecoderContextData;

class GLDecoder {
public:
    GLDecoder() {}
    ~GLDecoder() {}
    void setContextData(GLDecoderContextData *contextData) {
        (void)contextData;
    }
};
